[camera] Implement {GetMin|GetMax|Set}Exposure
flutter-tizen/plugins pull request #92
Opened 2021-05-10 11:10 UTC by bbrto21

This PR also incldues: 
* [camera] Introduce CameraDeviceError

2021-05-10 15:08 UTC, pwasowski2 requested changes
Besides a few minor defects, LGTM

2021-05-10 15:08 UTC, pwasowski2 commented on packages/camera/tizen/src/camera_device.cc
> +    GetRecorderFileName(file_name);
Shouldn't we check the error code here? If yes, please check the error code.

2021-05-11 00:14 UTC, bwikbs approved these changes
> I'm gonna to make a PR to merge this plugin to master after this PR

Thanks for working on the camera. I thought it would take a while, but It's not. :fireworks:

2021-05-11 00:31 UTC, bbrto21 commented on packages/camera/tizen/src/camera_device.cc
> +  if (min >= max) {
> > ```
> > If the min value is greater than the max value, it means that this feature is not supported. 
> > ```

You are right, but I found  a weird case with min and max are zero(front camera of TM1). In this case, the zoom behavior of the dart implementation is malfunctioning. I think that this is misleading, so I'll handle it as another if-statement

2021-05-11 00:46 UTC, bbrto21 commented on packages/camera/tizen/src/camera_device.cc
>      SetCameraPreviewFormat(pixel_format);
That's right, these things can fail depending on the device. But I did not check for errors intentionally.
This is to follow the original behavior and even if these two functions are failed, the Open must continue. 
And I think that there is nothing more to do at this time even if we check the return values(Each wrapper function logs an error)

2021-05-11 00:50 UTC, bbrto21 commented on packages/camera/tizen/src/camera_device.cc
> +        if (error == 0) {
the macro LOG_ERROR_IF is not have return statement

2021-05-11 00:54 UTC, bbrto21 commented on packages/camera/tizen/src/camera_device.cc
> +        LOG_ERROR_IF(error != MEDIA_PACKET_ERROR_NONE,
the macro LOG_ERROR_IF is not have return statement

2021-05-11 01:44 UTC, bbrto21 commented on packages/camera/tizen/src/camera_device.cc
> +          CameraDevice *camera_device = (CameraDevice *)data;
Thanks~

2021-05-11 06:40 UTC, pwasowski2 approved these changes
LGTM 👌

2021-05-11 10:37 UTC, bbrto21 commented on packages/camera/tizen/src/camera_device.cc
> +    // Not supported on TM1
No, according to the API documentation, it is not dependent on device.
I just wanted to notice that it is not supported on TM1 that is currently the only one device can be tested

2021-05-11 10:39 UTC, bbrto21 commented on packages/camera/tizen/src/camera_device.cc
> +              error.GetErrorMessage().c_str());
You are right, I'll change this to ```LOG_WARN```

2021-05-11 10:40 UTC, bbrto21 commented on packages/camera/tizen/src/camera_device.cc
> +    result->Error(kCameraDeviceError, "Failed to resume recorder");
I want to call UpdateStates for both cases.

2021-05-11 10:41 UTC, bbrto21 commented on packages/camera/tizen/src/camera_device.cc
> +    result->Error(kCameraDeviceError, "Failed to start recorder");
I want to call UpdateStates for both cases.

2021-05-11 11:33 UTC, pkosko approved these changes
👍

2021-05-13 01:22 UTC, merged